Test started for host : @ 13-04-2020 13:33:19
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03571358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:33:20
			Connection could not be esteablished
--------------------------------------------------
Test started for host : @ 13-04-2020 13:33:24
			google.ro
--------------------------------------------------
URL CHANGED @ 13-04-2020 13:33:26
			https://www.google.ro/?gws_rd=ssl
--------------------------------------------------
Waiting time for Python logo on main page excedeed @ 13-04-2020 13:33:31
			self.browser closed with error : Message: 

--------------------------------------------------
Unkown error @ 13-04-2020 13:33:37
			
--------------------------------------------------
Unkown error @ 13-04-2020 13:33:45
			
--------------------------------------------------
Error: 'NoneType' object has no attribute 'tag_name' @ 13-04-2020 13:33:49
			Element None does not have required attribute
--------------------------------------------------
Browser quit @ 13-04-2020 13:33:53
			Error:'NoneType' object has no attribute 'tag_name'
--------------------------------------------------
Test started for host : @ 13-04-2020 13:33:55
			python.org
--------------------------------------------------
Test started for host : @ 13-04-2020 13:34:41
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03231340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:34:42
			Connection could not be esteablished
--------------------------------------------------
Test started for host : @ 13-04-2020 13:34:46
			google.ro
--------------------------------------------------
URL CHANGED @ 13-04-2020 13:34:48
			https://www.google.ro/?gws_rd=ssl
--------------------------------------------------
Waiting time for Python logo on main page excedeed @ 13-04-2020 13:34:53
			self.browser closed with error : Message: 

--------------------------------------------------
Test started for host : @ 13-04-2020 13:36:01
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03111358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:36:02
			Connection could not be esteablished
--------------------------------------------------
Test started for host : @ 13-04-2020 13:36:06
			google.ro
--------------------------------------------------
URL CHANGED @ 13-04-2020 13:36:08
			https://www.google.ro/?gws_rd=ssl
--------------------------------------------------
Waiting time for Python logo on main page excedeed @ 13-04-2020 13:36:13
			self.browser closed with error : Message: 

--------------------------------------------------
Unkown error @ 13-04-2020 13:36:20
			
--------------------------------------------------
Unkown error @ 13-04-2020 13:36:28
			
--------------------------------------------------
Error: 'NoneType' object has no attribute 'tag_name' @ 13-04-2020 13:36:32
			Element None does not have required attribute
--------------------------------------------------
Testing case no. @ 13-04-2020 13:39:10
			Testing case no. @ 13-04-2020 13:39:55
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 13:39:55
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0311B640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:39:55
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:39:58
			
--------------------------------------------------
Testing case no. @ 13-04-2020 13:42:24
			2
--------------------------------------------------
Testing case no. @ 13-04-2020 13:43:02
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:02
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0311B640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:43:02
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:43:04
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:04
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64700): Max retries exceeded with url: /session/b60528880f95ac8a77ef7afe347c0ca5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033D12B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:43:09
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:43:13
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:13
			python.org
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64700): Max retries exceeded with url: /session/b60528880f95ac8a77ef7afe347c0ca5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033D1850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:43:18
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:43:22
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:22
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64700): Max retries exceeded with url: /session/b60528880f95ac8a77ef7afe347c0ca5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0311B478>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:43:27
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:43:31
			
--------------------------------------------------
Testing case no. @ 13-04-2020 13:43:42
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:42
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x039CB640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:43:43
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:43:45
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:45
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64776): Max retries exceeded with url: /session/6005b4c21a41673fb20ee650c474a3cc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03C81280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:43:49
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:43:53
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:43:53
			python.org
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64776): Max retries exceeded with url: /session/6005b4c21a41673fb20ee650c474a3cc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03C81820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:43:58
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:44:02
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:44:02
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64776): Max retries exceeded with url: /session/6005b4c21a41673fb20ee650c474a3cc/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x039CB478>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:44:08
			Connection could not be esteablished
--------------------------------------------------
Testing case no. @ 13-04-2020 13:44:52
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 13:44:52
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0376C640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:44:52
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:44:54
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:44:54
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64892): Max retries exceeded with url: /session/51e0505864cd431654623d4955ed1f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03A21298>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:44:59
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:45:03
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:45:03
			python.org
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64892): Max retries exceeded with url: /session/51e0505864cd431654623d4955ed1f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03A21838>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:45:08
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:45:12
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:45:12
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=64892): Max retries exceeded with url: /session/51e0505864cd431654623d4955ed1f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0376C478>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:45:17
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:45:21
			
--------------------------------------------------
Testing case no. @ 13-04-2020 13:54:16
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 13:54:16
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0359B640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 13:54:16
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:54:18
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:54:18
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=49606): Max retries exceeded with url: /session/068542ba2a7b7bb7a1246cf61355a032/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03851298>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:54:22
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:54:26
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:54:26
			python.org
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=49606): Max retries exceeded with url: /session/068542ba2a7b7bb7a1246cf61355a032/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03851838>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:54:31
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:54:35
			
--------------------------------------------------
Test started for host : @ 13-04-2020 13:54:35
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=49606): Max retries exceeded with url: /session/068542ba2a7b7bb7a1246cf61355a032/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0359B478>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 13:54:40
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 13:54:44
			
--------------------------------------------------
Testing case no. @ 13-04-2020 14:00:08
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 14:00:08
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0314B670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 14:00:08
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:00:10
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:00:10
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=50284): Max retries exceeded with url: /session/66701500631cb2baecabb601597c24b0/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0314B400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:00:15
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:00:19
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:00:19
			python.org
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=50284): Max retries exceeded with url: /session/66701500631cb2baecabb601597c24b0/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033E1730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:00:27
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:00:31
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:00:31
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=50284): Max retries exceeded with url: /session/66701500631cb2baecabb601597c24b0/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033E1358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:00:38
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:00:42
			
--------------------------------------------------
Testing case no. @ 13-04-2020 14:04:51
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 14:04:51
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0319B508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 14:04:51
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:04:54
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:04:54
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=50795): Max retries exceeded with url: /session/b8f63969f35f16f934cd828a372ece6c/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03453160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:04:58
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:05:02
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:05:02
			python.org
--------------------------------------------------
Connection ERROR:
HTTPSConnectionPool(host='python.org', port=443): Max retries exceeded with url: https://python.org/ (Caused by ResponseError('too many redirects')) @ 13-04-2020 14:05:03
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:05:07
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:05:07
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=50795): Max retries exceeded with url: /session/b8f63969f35f16f934cd828a372ece6c/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03453BC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:05:11
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:05:15
			
--------------------------------------------------
Testing case no. @ 13-04-2020 14:09:02
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 14:09:02
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0311B508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 14:09:02
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:09:04
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:09:04
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=51119): Max retries exceeded with url: /session/8cb60c181ba7d60daee2cfd125c2d33e/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033D4130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:09:09
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:09:13
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:09:13
			python.org
--------------------------------------------------
Connection ERROR:
HTTPSConnectionPool(host='python.org', port=443): Max retries exceeded with url: https://python.org/ (Caused by ResponseError('too many redirects')) @ 13-04-2020 14:09:13
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:09:18
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:09:18
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=51119): Max retries exceeded with url: /session/8cb60c181ba7d60daee2cfd125c2d33e/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033D4B98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:09:23
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:09:27
			
--------------------------------------------------
Testing case no. @ 13-04-2020 14:22:27
			2
--------------------------------------------------
Test started for host : @ 13-04-2020 14:22:27
			scratchpd.com
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='scratchpd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0314B658>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) @ 13-04-2020 14:22:28
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:22:30
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:22:30
			google.ro
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=52165): Max retries exceeded with url: /session/4e5b7f2287513ce509cf2da28af65e25/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033E12E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:22:34
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:22:38
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:22:38
			python.org
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=52165): Max retries exceeded with url: /session/4e5b7f2287513ce509cf2da28af65e25/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033E1880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:22:43
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:22:48
			
--------------------------------------------------
Test started for host : @ 13-04-2020 14:22:48
			www.bitacad.net
--------------------------------------------------
Connection ERROR:
HTTPConnectionPool(host='127.0.0.1', port=52165): Max retries exceeded with url: /session/4e5b7f2287513ce509cf2da28af65e25/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0314B490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')) @ 13-04-2020 14:22:53
			Connection could not be esteablished
--------------------------------------------------
Browser exited with error @ 13-04-2020 14:22:57
			
--------------------------------------------------
